tests: check decoding with ASN1_DECODE_FLAG_ALLOW_INCORRECT_TIME flag
Signed-off-by: Nikos Mavrogiannopoulos <nmav@redhat.com>

diff --git a/tests/decoding b/tests/decoding
--- a/tests/decoding
+++ b/tests/decoding
@@ -28,4 +28,18 @@ if test $? != 1;then
 	exit 1
 fi
 
+# test decoding of certificate with invalid time field
+$VALGRIND $ASN1DECODING -s $ASN1PKIX cert-invalid-time.der PKIX1.Certificate
+if test $? != 1;then
+	echo "Decoding with invalid time succeeded when not expected"
+	exit 1
+fi
+
+# test decoding of certificate with invalid time field
+$VALGRIND $ASN1DECODING -t $ASN1PKIX cert-invalid-time.der PKIX1.Certificate
+if test $? != 0;then
+	echo "Decoding with invalid time failed when not expected"
+	exit 1
+fi
+
 exit 0
