tests: added several invalid certificates
Provided by Pascal Cuoq.

diff --git a/tests/decoding-invalid-x509 b/tests/decoding-invalid-x509
--- a/tests/decoding-invalid-x509
+++ b/tests/decoding-invalid-x509
@@ -29,8 +29,9 @@ ASN1PKIX="${ASN1PKIX:-pkix.asn}"
 
 for i in "${srcdir}/invalid-x509/"*.der;do
 $VALGRIND $ASN1DECODING "$ASN1PKIX" "$i" PKIX1.Certificate >/dev/null 2>&1
-if test $? != 1;then
-	echo "Decoding failed"
+ret=$?
+if test $ret != 1;then
+	echo "Decoding failed for $i"
 	exit 1
 fi
 echo "$(basename $i): ok"
